ДЗ 1
kontsovart/2020-1-Atom-QA-Python-A-Kontsov pull request #1
Opened 2020-03-11 13:59 UTC by kontsovart

# Домашнее задание №1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
Написаны по 5 автотестов с учетом техних тест-дизайна на каждую из структур данных в Python:
    List
    Set
    Dictionary
    String
    Int

2020-03-12 14:54 UTC, sniiick requested changes
Давай положим тесты на конкретную структуру по отдельным папкам, а фикстуры в conftest.
Все остально ок

2020-03-13 20:53 UTC, kontsovart commented
> Давай положим тесты на конкретную структуру по отдельным папкам, а фикстуры в conftest.
> Все остально ок

Исправил структуру и удалил старые файлы

2020-03-13 20:55 UTC, kontsovart commented
Исправлены замечания по структуре проекта

2020-03-13 23:12 UTC, sniiick approved these changes

2020-03-13 23:12 UTC, merged